
# Updates for the gender_violence database (procedure 1)
updates_gender_violence = [
    ["Gender Violence against Women", "Women who have experienced physical and/or psychological violence, threats and sexual violence from a any perpetrator."],
    ["Domestic Gender Violence against Women", "Women who have experienced physical and/or psychological violence, threats and sexual violence from a domestic perpetrator."],
    ["Intimate Gender Violence against Women", "Women who have experienced physical and/or psychological violence, threats and sexual violence from an intimate partner."],
    ["Non Intimate Gender Violence against Women", "Women who have experienced physical and/or psychological violence, threats and sexual violence from a non intimate partner."],
    ["Gender Violence by occurence", "Women who have experienced violence in adulthood, last 12 months or last 5 years from any perpetrator."],
    ["Domestic Gender Violence by occurence", "Women who have experienced violence in adulthood, last 12 months or last 5 years from a domestic perpetrator."],
    ["Intimate Gender Violence by occurence", "Women who have experienced violence in adulthood, last 12 months or last 5 years from an intimate partner."],
    ["Non Intimate Gender Violence by occurence", "Women who have experienced violence in adulthood, last 12 months or last 5 years from a non intimate partner."],
    ["Gender Violence by Age", "Women who have experienced violence by age groups from any perpetrator."],
    ["Domestic Gender Violence by Age", "Women who have experienced violence by age groups from a domestic perpetrator."],
    ["Intimate Gender Violence by Age", "Women who have experienced violence by age groups from an intimate partner."],
    ["Non Intimate Gender Violence by Age", "Women who have experienced violence by age groups from a non intimate partner."],
    ["Gender Violence by Reporting", "Women who have experienced violence by any perpetrator and reported to a close person, health or social service, support service, police or any person."],
    ["Intimate Gender Violence by Reporting", "Women who have experienced violence by an intimate partner and reported to a close person, health or social service, support service, police or any person."],
    ["Non Intimate Gender Violence by Reporting", "Women who have experienced violence by a non intimate partner and reported to a close person, health or social service, support service, police or any person."],
    ["Gender Violence by Consequences", "Women who have experienced Physical injury, Psychological consequences or have Felt that their life was in danger after violence from any perpetrator."],
    ["Intimate Gender Violence by Consequences", "Women who have experienced Physical injury, Psychological consequences or have Felt that their life was in danger after violence from an intimate partner."],
    ["Non Intimate Gender Violence by Consequences", "Women who have experienced Physical injury, Psychological consequences or have Felt that their life was in danger after violence from a non intimate partner."],
    ["Gender Violence by Victim limitations", "Women with None, Some, Severe or limited level of disability (activity limitation) who have experienced violence from any perpetrator."],
    ["Domestic Gender Violence by Victim limitations", "Women with None, Some, Severe or limited level of disability (activity limitation) who have experienced violence from a domestic perpetrator."],
    ["Intimate Gender Violence by Victim limitations", "Women with None, Some, Severe or limited level of disability (activity limitation) who have experienced violence from an intimate partner."],
    ["Non Intimate Gender Violence by Victim limitations", "Women with None, Some, Severe or limited level of disability (activity limitation) who have experienced violence from a non intimate partner."],
    ["Gender Violence by Victim education", "Women with less than primary, primary and lower secondary, upper secondary or tertiary education (ISCED levels 0-2, 3-4, 5-8) who have experienced violence from any perpetrator."],
    ["Domestic Gender Violence by Victim education", "Women with less than primary, primary and lower secondary, upper secondary or tertiary education (ISCED levels 0-2, 3-4, 5-8) who have experienced violence from a domestic perpetrator."],
    ["Intimate Gender Violence by Victim education", "Women with less than primary, primary and lower secondary, upper secondary or tertiary education (ISCED levels 0-2, 3-4, 5-8) who have experienced violence from an intimate partner."],
    ["Non Intimate Gender Violence by Victim education", "Women with less than primary, primary and lower secondary, upper secondary or tertiary education (ISCED levels 0-2, 3-4, 5-8) who have experienced violence from a non intimate partner."],
    ["Gender Violence by Victim residence", "Women with residence in Cities, Towns or Rural areas who have experienced violence from any perpetrator."],
    ["Domestic Gender Violence by Victim residence", "Women with residence in Cities, Towns or Rural areas who have experienced violence from a domestic perpetrator."],
    ["Intimate Gender Violence by Victim residence", "Women with residence in Cities, Towns or Rural areas who have experienced violence from an intimate partner."],
    ["Non Intimate Gender Violence by Victim residence", "Women with residence in Cities, Towns or Rural areas who have experienced violence from a non intimate partner."],
    ["Gender Violence by Victim nationality", "Women from EU, Non-EU or Reporting countries except reporting country who have experienced violence from any perpetrator."],
    ["Domestic Gender Violence by Victim nationality", "Women from EU, Non-EU or Reporting countries except reporting country who have experienced violence from a domestic perpetrator."],
    ["Intimate Gender Violence by Victim nationality", "Women from EU, Non-EU or Reporting countries except reporting country who have experienced violence from an intimate partner."],
    ["Non Intimate Gender Violence by Victim nationality", "Women from EU, Non-EU or Reporting countries except reporting country who have experienced violence from a non intimate partner."],
    ["Gender Violence by relation", "Women who have experienced repeated violence by partner - male or female - non partner or family member."],
    ["Intimate Gender Violence by relation", "Women who have experienced repeated violence by partner - male or female - non partner or family member."],
    ["Non Intimate Gender Violence by relation", "Women who have experienced repeated violence by partner - male or female - non partner or family member."],
    ["Repeated Gender Violence", "Women who have experienced repeated violence At least once a week, less than once a month or at least once a month from any perpetrator."],
    ["Intimate Repeated Gender Violence", "Women who have experienced repeated violence At least once a week, less than once a month or at least once a month from an intimate partner."],
    ["Non Intimate Repeated Gender Violence", "Women who have experienced repeated violence At least once a week, less than once a month or at least once a month from a non intimate partner."],
    ["Gender Violence by duration", "Women who have experienced repeated violence for less than 1 year, for from 1 to 5 years and for over 5 years from any perpetrator."],
    ["Intimate Gender Violence by duration", "Women who have experienced repeated violence for less than 1 year, for from 1 to 5 years and for over 5 years from an intimate partner."],
    ["Non Intimate Gender Violence by duration", "Women who have experienced repeated violence for less than 1 year, for from 1 to 5 years and for over 5 years from a non intimate partner."],
    ["Intimate Economic Gender Violence by age", "Women who have experienced economic violence (forbidding the respondent to work, controlling the finances of the whole family) by age groups from an intimate partner."],
    ["Gender Violence by injury occurence", "Women who have experienced injuries after violence in adulthood, last 12 months or last 5 years by any perpetrator."],
]